# Site settings
title: 墨竹林
layout: posts
email: pyericz@yahoo.com 
# description: "张培养的博客"
brief-intro: "张培养的点滴记录"
baseurl: ""
url: "http://www.pyericz.com/"
description_footer: 日晚爱行深竹里，月明躲在小桥头
github_username:  pyericz
timezone: Asian/Shanghai

author: Eric Zhang

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
permalink: pretty

highlighter: rouge
github: https://github.com/pyericz/pyericz.github.io.git

#permalink: pretty
excerpt_separator: "\n\n\n"

category_dir: category/
tag_dir: tag/

gems: [jekyll-paginate]
paginate: 10

baidu_tongji_id: 771bb69fe07c2dc990235fa69f556948
google_analytics_id: UA-104881843-1
