# Site settings
title: 艾里克de梦
layout: posts
email: pyericz@yahoo.com 
description: ""
baseurl: ""
url: "http://pyericz.github.io"
github_username:  pyericz
timezone: Asian/Shanghai

author: Eric Zhang

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]
permalink: pretty

highlighter: rouge
github: https://github.com/pyericz/pyericz.github.io.git

theme: jekyll-theme-hacker
