# Site settings
title: PxrGO
layout: posts
email: pyericz@yahoo.com 
description: "一抹午烟风隔断，野鸡声在竹林西。追求知识，领悟智慧，淡定从容。科学、技术、思辨与随笔，用博客记录人生感悟。"
brief-intro: "追求知识，领悟智慧，淡定从容"
baseurl: ""
url: "http://www.pxrgo.com/"
description_footer: 一抹午烟风隔断，野鸡声在竹林西
github_username:  pyericz
timezone: Asian/Shanghai

author: pyericz

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
permalink: pretty

highlighter: rouge
github: https://github.com/pyericz/pyericz.github.io.git

#permalink: pretty
excerpt_separator: "\n\n\n"

category_dir: category/
tag_dir: tag/

gems: [jekyll-paginate]
paginate: 10

baidu_tongji_id: af70bfc5da9448bfc976050e257c12fe
google_analytics_id: UA-104881843-1
twitter_username: PxrGO
zhihu_username: pxrgo
quora_username: PxrGO
