# Site settings
title: 艾里克de梦
layout: posts
email: pyericz@yahoo.com 
description: ""
baseurl: ""
url: "http://www.pyericz.com/"
github_username:  pyericz
timezone: Asian/Shanghai

author: Eric Zhang

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
permalink: pretty

highlighter: rouge
github: https://github.com/pyericz/pyericz.github.io.git

#permalink: pretty
excerpt_separator: "\n\n\n"

category_dir: category/
tag_dir: tag/

gems: [jekyll-paginate]
paginate: 10
# theme: jekyll-theme-hacker
